#pragma once
#include <lvgl.h>
#include <string>
class Tile;
class Label;
class Image;
class Chart;
class Dropdown;
class Container;

static size_t id_generator;
static size_t nextId() {
  return id_generator++;
}
static std::string nextIdString() {
  return "__id" + std::to_string(nextId());
}

/// # Widget Container
/// this class is the baseline to all widgets (as all widgets in LVGL are really in themselves containers)
/// under the hood this wrappers uses the ``user_data`` field in the wrapped widget as a reference counter
/// in order to allow cloning of the widget container object.
class WidgetContainer {
 private:
  //Pointer to the widget being wrapped
  lv_obj_t* widget_ptr;

 protected:
  //override copy and move constructors to allow for reference counting
  WidgetContainer(WidgetContainer&& other);
  WidgetContainer(const WidgetContainer& other);

  //override copy and move assignments to allow for reference counting
  WidgetContainer& operator=(const WidgetContainer& other);
  WidgetContainer& operator=(WidgetContainer&& other);

  //hidden constructor that should be given an untouched, initialized ``lv_obj_t`` pointer. Generated by one of LVGL's functions.
  WidgetContainer(lv_obj_t* widget);

  size_t getRefCount();
  void setRefCount(size_t count);

 public:
  //getter function for the underlying widget pointer
  lv_obj_t* getWidgetPtr() const { return widget_ptr; }

  //Add a new label widget as the child of this widget container
  virtual Container& addContainer(std::string name = nextIdString()) = 0;

  //Add a new label widget as the child of this widget container
  virtual Label& addLabel(std::string name = nextIdString()) = 0;

  //Add a new label widget as the child of this widget container
  virtual Image& addImage(std::string name = nextIdString()) = 0;

  //Add a new label widget as the child of this widget container
  virtual Dropdown& addDropdown(std::string name = nextIdString()) = 0;

  //Add a new label widget as the child of this widget container
  virtual Chart& addChart(std::string name = nextIdString()) = 0;

  //Get a reference to the parent tile container
  virtual Tile& getTile() = 0;

  //Get a reference to the parent widget/container
  virtual WidgetContainer& getParent() = 0;

  // Set up this widget as a flex container
  WidgetContainer& setFlexLayout(
      lv_flex_flow_t flex_flow, lv_flex_align_t main_align,
      lv_flex_align_t cross_align = LV_FLEX_ALIGN_CENTER,
      lv_flex_align_t cross_place = LV_FLEX_ALIGN_CENTER);

  // Set up this widget as a grid container
  WidgetContainer& setGridLayout(const int32_t col_dsc[],
                                 const int32_t row_dsc[]);

  // Sizing

  // # Set size of the widget
  WidgetContainer& setSize(int32_t w, int32_t h);

  // # Set width of the widget
  WidgetContainer& setWidth(int32_t w);

  // # Set height of the widget
  WidgetContainer& setHeight(int32_t h);

  // # Set content width of the widget
  WidgetContainer& setContentWidth(int32_t w);

  // # Set content height of the widget
  WidgetContainer& setContentHeight(int32_t h);

  //Destructor (which deletes and cleans the widget if and only if it holds the last reference to it)
  ~WidgetContainer();

  friend class Tile;
};
