#ifndef GUI_WIDGET_H
#define GUI_WIDGET_H

#include "lvgl/lvgl.h"

#include <unordered_map>
#include <utility>
#include <memory>
#include <string>
#include <vector>

class Tile;
class Label;
class Image;
class Chart;
class Dropdown;


static size_t id_generator;
static size_t nextId() {
    return id_generator++;
}
static std::string nextIdString() {
    return "__id" + std::to_string(nextId());
}

/// # Widget Container
/// this class is the baseline to all widgets (as all widgets in LVGL are really in themselves containers)
/// under the hood this wrappers uses the ``user_data`` field in the wrapped widget as a reference counter
/// in order to allow cloning of the widget container object.
class WidgetContainer {
    private:
        //Pointer to the widget being wrapped
        lv_obj_t* widget_ptr;

    protected:
        //override copy and move constructors to allow for reference counting
        WidgetContainer(WidgetContainer&& other);
        WidgetContainer(const WidgetContainer& other);

        //override copy and move assignments to allow for reference counting
        WidgetContainer& operator=(const WidgetContainer& other);
        WidgetContainer& operator=(WidgetContainer&& other);

        //hidden constructor that should be given an untouched, initialized ``lv_obj_t`` pointer. Generated by one of LVGL's functions.
        WidgetContainer(lv_obj_t* widget);

        size_t getRefCount();
        void setRefCount(size_t count);
    public:
        //getter function for the underlying widget pointer
        lv_obj_t* getWidgetPtr() const { return widget_ptr; }

        //Add a new label widget as the child of this widget container
        virtual Label& addLabel(std::string name) = 0;


        //Add a new label widget as the child of this widget container
        virtual Image& addImage(std::string name) = 0;


        //Add a new label widget as the child of this widget container
        virtual Dropdown& addDropdown(std::string name) = 0;


        //Add a new label widget as the child of this widget container
        virtual Chart& addChart(std::string name) = 0;
        
        //Get a reference to the parent tile container
        virtual Tile& getTile() = 0;
        
        //Get a reference to the parent widget/container
        virtual WidgetContainer& getParent() = 0;

        // Set up this widget as a flex container
        WidgetContainer& setFlexLayout(lv_flex_flow_t flex_flow, lv_flex_align_t main_align, lv_flex_align_t cross_align = LV_FLEX_ALIGN_CENTER, lv_flex_align_t cross_place = LV_FLEX_ALIGN_CENTER);

        // Set up this widget as a grid container
        WidgetContainer& setGridLayout(const int32_t col_dsc[], const int32_t row_dsc[]);

        //Destructor (which deletes and cleans the widget if and only if it holds the last reference to it)
        ~WidgetContainer();

    friend class Tile;
};

/// # Widget
/// this class implements all generic widget functions from LVGL and should be inherited from for specifi widget wrappers
class Widget: public WidgetContainer {
    private:
        WidgetContainer* parent;
        Tile* tile;
        uint32_t id;
    protected:
        //Object constructor
        Widget(WidgetContainer& parent, lv_obj_t* widget, uint32_t id);
    public:

        // # Destructor function
        ~Widget() {}

        // # Get Parent tile of this Widget
        Tile& getTile() override;

        // # Add label as child of this widget
        Label& addLabel(std::string name) override;
        // # Add label as child of this widget
        Chart& addChart(std::string name) override;
        // # Add label as child of this widget
        Image& addImage(std::string name) override;
        // # Add label as child of this widget
        Dropdown& addDropdown(std::string name) override;

        // # Get parent of this widget
        WidgetContainer& getParent() override;

        // # Add an event callback to the widget
        Widget& addEventCallback(lv_event_cb_t event_cb, lv_event_code_t filter, void *user_data = nullptr);


        //FLAGS

        // # Add a widget flag to the widget
        Widget& addFlag(lv_obj_flag_t flag);

        // # Remove a widget flag to the widget
        Widget& removeFlag(lv_obj_flag_t flag);


        // Positioning

        // # Set position of the widget
        Widget& setPos(int32_t x, int32_t y);

        // # Set the X coordinate of the widget
        Widget& setX(int32_t x);

        // # Set the Y coordinate of the widget
        Widget& setY(int32_t y);

        // # Set the alignment type of the widget
        Widget& setAlign(lv_align_t align);

        // # Set the alignment and offset relative to widget parent
        Widget& align(lv_align_t align, int32_t x_offset, int32_t y_offset);

        // # Set the alignment and offset relative to arbitrary widget
        Widget& alignTo(Widget& base, lv_align_t align, int32_t x_offset, int32_t y_offset);

        // # Center widget
        Widget& center();

        // # Set position of the widget
        Widget& setGridCell(int32_t row_pos, int32_t col_pos, int32_t row_span = 1, int32_t col_span = 1, lv_grid_align_t row_align = LV_GRID_ALIGN_CENTER, lv_grid_align_t column_align = LV_GRID_ALIGN_CENTER);

        // Sizing

        // # Set size of the widget
        Widget& setSize(int32_t w, int32_t h);

        // # Set width of the widget
        Widget& setWidth(int32_t w);

        // # Set height of the widget
        Widget& setHeight(int32_t h);

        // # Set content width of the widget
        Widget& setContentWidth(int32_t w);

        // # Set content height of the widget
        Widget& setContentHeight(int32_t h);

        // Other Styling

        ///# Widget::setFont
        /// @brief Set the font styling of the label
        /// @param font the LVGL font for this label to use 
        /// @param selector the part of the label the font applies to (by default the main text)
        /// @return A new reference to the calling label
        Widget& setFont(const lv_font_t* font, lv_style_selector_t selector = LV_PART_MAIN);
};
#endif
